### ISSUE TITLE
Only reproducible on a Mac

### ISSUE THREAD

**Issue by wdroste** [vert-x3/vertx-stomp#31]
JAVA 1.8_144

Tried it against 3.4.0, 3.4.1, 3.5.0-SNAPSHOT

We built a stomp client that is reliably getting this error on Mac but not on our linux boxes.. it looks like there's a logic error or weirdness in a data handler.. 

`SEVERE: Unhandled exception
java.lang.IllegalArgumentException: end must be greater or equal than start
        at io.vertx.core.impl.Arguments.require(Arguments.java:34)
        at io.vertx.core.buffer.impl.BufferImpl.getBytes(BufferImpl.java:169)
        at io.vertx.core.buffer.impl.BufferImpl.getBuffer(BufferImpl.java:198)
        at io.vertx.core.parsetools.impl.RecordParserImpl.parseDelimited(RecordParserImpl.java:182)
        at io.vertx.core.parsetools.impl.RecordParserImpl.handleParsing(RecordParserImpl.java:159)
        at io.vertx.core.parsetools.impl.RecordParserImpl.handle(RecordParserImpl.java:218)
        at io.vertx.ext.stomp.impl.FrameParser.handle(FrameParser.java:221)
        at io.vertx.ext.stomp.impl.StompClientConnectionImpl.lambda$new$2(StompClientConnectionImpl.java:105)
        at io.vertx.core.net.impl.NetSocketImpl.handleDataReceived(NetSocketImpl.java:325)
        at io.vertx.core.net.impl.NetClientImpl.handleMsgReceived(NetClientImpl.java:101)
        at io.vertx.core.net.impl.NetClientImpl.handleMsgReceived(NetClientImpl.java:45)
        at io.vertx.core.net.impl.NetClientBase$1.handleMsgReceived(NetClientBase.java:189)
        at io.vertx.core.net.impl.VertxNetHandler.lambda$channelRead$0(VertxNetHandler.java:63)
`

**Comment by cescoffier** [comment]
Can you provide a reproducer? 
It looks like the receive buffer is empty.

**Comment by wdroste** [comment]
This on the 'connect' not even during some interaction, will try to get a pcap tomorrow the machine is not mine and he has gone for the day. Yeah its frustrating because I would have fixed it if had been reproducible on my workstation. Thought I let you know though we saw this, in case it was known.

**Comment by wdroste** [comment]
@cescoffier not an issue, turned out home brew will install RabbitMQ w/ the stomp plugin enabled by default, this not an issue w/ Vertx. I didn't see the couldn't bind on the default stomp port.

Summary not a Vertx issue closing, thank you for responding so quickly.

**Comment by cescoffier** [comment]
Thanks for the feedback @wdroste !
