### ISSUE TITLE
Only half available ports can be bond when set both localAddress and setReuseAddress as true in the StompClientOptions 

### ISSUE THREAD

**Issue by deepsleep** [vert-x3/vertx-stomp#43]
Hi there, I was doing performance testing on a vertx-stomp based application, and we use StompClient to generate large number of stomp clients. 

I found a weird issue that when setting both `setLocalAddress(localAddress)` and `setReuseAddress(true)`, the StompClient can only bind about half of the available ports on linux(CentOS 7 and Ubuntu 16.4). And I also tested on macOS, it does not have this issue. And when setting setReuseAddress(false) does not have this issue neither.
All of the testing are running on the Hotspot jdk 8 build #162

You can reproduce this issue by using the attached jar by follow steps.

0. Download the source code attached in the zip and build with maven. A jar file `test-stomp-0.0.1-jar-with-dependencies.jar` will be generated.

1. Start up the MyStompServer
`  java -jar test-stomp-0.0.1-jar-with-dependencies.jar`

2. Narrow the ip_local_port_range to 10 avaialbe by running below command in the client server
`sysctl -w 'net.ipv4.ip_local_port_range=61000 61009'`

3. Connected 10 clients to the Stomp server
   ` java -Djava.net.preferIPv4Stack=true -cp test-stomp-0.0.1-jar-with-dependencies.jar test.stomp.MyStompClient 10 true <clientIPAddr> <serverIPAddr>`
    Here, 10 is start up 10 clients, true is set setReuseAddress as true in the StompClientOptions.

Then there are only 5 clients can be start up and check by using netstat -nt|grep 61613 in the client server(192.168.0.178)

tcp  |   0   |   0 192.168.0.178:61000 |   192.168.0.84:61613  |  ESTABLISHED
tcp  |   0   |   0 192.168.0.178:61004 |   192.168.0.84:61613  |  ESTABLISHED
tcp  |   0   |   0 192.168.0.178:61001 |   192.168.0.84:61613  |  ESTABLISHED
tcp  |   0   |   0 192.168.0.178:61002 |   192.168.0.84:61613  |  ESTABLISHED
tcp  |   0   |   0 192.168.0.178:61003 |   192.168.0.84:61613  |  ESTABLISHED

And there are exception as below:

```
io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
    at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:310)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
    at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1000)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:264)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:254)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
    ... 22 more
Failed to connect to the STOMP server: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
    at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:310)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
    at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1000)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:264)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:254)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
    ... 22 more
Failed to connect to the STOMP server: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
    at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:310)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
    at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1000)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:264)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:254)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
    ... 22 more
Failed to connect to the STOMP server: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
    at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:310)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
    at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1000)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:264)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:254)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
    ... 22 more
Failed to connect to the STOMP server: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Net.java:454)
    at sun.nio.ch.Net.connect(Net.java:446)
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:83)
    at io.netty.util.internal.SocketUtils$3.run(SocketUtils.java:80)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.connect(SocketUtils.java:80)
    at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:310)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1291)
    at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1000)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:264)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:254)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Cannot assign requested address
    ... 22 more
Failed to connect to the STOMP server: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: /192.168.0.84:61613

3 Receive ping from server at 5186310942605173
1 Receive ping from server at 5186310946579101
0 Receive ping from server at 5186310947877513
4 Receive ping from server at 5186310949324149
2 Receive ping from server at 5186310950959071
```

When run below, there are 10 clients can be run and no exceptions print out.    
`java -Djava.net.preferIPv4Stack=true -cp test-stomp-0.0.1-jar-with-dependencies.jar test.stomp.MyStompClient 10 fase <clientIPAddr> <serverIPAddr>`

F.Y.I. The attached jar is the stomp server and client used above. And the zip file is the full src code with maven pom. And for your better reading, I copy the startAClient method from MyStompClient as below

```
 public void startAClient(String localIP, String remoteIP, int id, boolean reuseAddress) throws UnknownHostException {
        StompClientOptions options = new StompClientOptions();
        options.setHeartbeat(new JsonObject().put("x", 1000).put("y", 1000));
        options.setLocalAddress(localIP);
        options.setReuseAddress(reuseAddress);
        StompClient client = StompClient.create(vertx,options) .receivedFrameHandler(frame -> {
            if(Frame.Command.PING.equals(frame.getCommand())) {
                System.out.println(id + " Receive ping from server at "  + System.nanoTime());
            }
        });
        client .connect(61613, remoteIP, ar -> {
            if (ar.succeeded()) {
                StompClientConnection connection = ar.result();
            } else {
                Exception e = (Exception) ar.cause();
                e.printStackTrace();
                System.out.println("Failed to connect to the STOMP server: " + ar.cause());
            } });
    }
```
[teststomp.zip](https://github.com/vert-x3/vertx-stomp/files/2179663/teststomp.zip)

**Comment by cescoffier** [comment]
PR merged.
